name: Terraform FMT & Validate

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: TF Workflow 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.7

    - name: Terraform Init
      run: terraform init 

    - name: Terraform FMT
      run: |
        terraform fmt -check -recursive
      continue-on-error: false

    - name: Terraform Validate
      run: terraform validate